### ISSUE TITLE
Fix pre-commit

### ISSUE THREAD

**Issue by chrisleee** [ChrisALee/twitch-stocks#62]
I temporarily removed the hook, so it doesn't actually do anything at the moment.

**Comment by jallier** [comment]
I've been looking into this, I think its due to there being 3 package.json files. I tried using one 'master' package.json file in the root dir in addition to the other 3, but that didn't seem to work. 

Temporary workaround is disable completely and ask contributors to run `npm run lint-staged` on their staged files before every commit, or provide pre-commit hooks we can install locally. 
See #65

**Comment by chrisleee** [comment]
#69
